
TYPE
	E_CODE_STEP : 
		(
		CODE_WAIT := 0,
		CODE_CHECK_TRIG := 100,
		CODE_GET_SH := 200,
		CODE_MOVE_TO_READER := 300,
		CODE_READER_CHECK := 400,
		CODE_CHECK_TAKE_COUNT := 500,
		CODE_ID_DEFINE := 600,
		CODE_RELEASE_SH := 700,
		CODE_NORMAL_END := 1000
		) := CODE_WAIT;
END_TYPE
